// <auto-generated />
using System;
using AlanTuring.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AlanTuring.Migrations
{
    [DbContext(typeof(Alan_TuringContext))]
    partial class Alan_TuringContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Cyrillic_General_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AlanTuring.Models.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int>("PathsId")
                        .HasColumnType("int")
                        .HasColumnName("paths_ID");

                    b.Property<int>("CoursesId")
                        .HasColumnType("int")
                        .HasColumnName("courses_ID");

                    b.Property<int>("DeclarativeLessonsId")
                        .HasColumnType("int")
                        .HasColumnName("declarative_Lessons_ID");

                    b.Property<int>("LessonsId")
                        .HasColumnType("int")
                        .HasColumnName("lessons_ID");

                    b.Property<int>("AssignmentsIdentity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("assignments_identity")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Datetime")
                        .HasColumnType("datetime")
                        .HasColumnName("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime")
                        .HasColumnName("dueDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id", "PathsId", "CoursesId", "DeclarativeLessonsId", "LessonsId")
                        .HasName("Assignments_pk");

                    b.HasIndex("CoursesId");

                    b.HasIndex("DeclarativeLessonsId");

                    b.HasIndex("LessonsId");

                    b.HasIndex("PathsId");

                    b.HasIndex(new[] { "Id" }, "UQ__Assignme__3214EC2672E9EF64")
                        .IsUnique();

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("AlanTuring.Models.Chat", b =>
                {
                    b.Property<int>("MessageId")
                        .HasColumnType("int")
                        .HasColumnName("message_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime")
                        .HasColumnName("date");

                    b.Property<int?>("GroupReceiverId")
                        .HasColumnType("int")
                        .HasColumnName("group_receiver_id");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("message_content");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("name");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.Property<int?>("UserReceiverId")
                        .HasColumnType("int")
                        .HasColumnName("user_receiver_id");

                    b.Property<int?>("UserSenderId")
                        .HasColumnType("int")
                        .HasColumnName("user_sender_id");

                    b.HasKey("MessageId")
                        .HasName("PK__Chats__0BBF6EE6DEFE4AFE");

                    b.HasIndex("GroupReceiverId");

                    b.HasIndex("UserReceiverId");

                    b.HasIndex("UserSenderId");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("AlanTuring.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int?>("AssignmentsId")
                        .HasColumnType("int")
                        .HasColumnName("assignments_ID");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int?>("CoursesId")
                        .HasColumnType("int")
                        .HasColumnName("courses_ID");

                    b.Property<DateTime>("Datetime")
                        .HasColumnType("datetime")
                        .HasColumnName("datetime");

                    b.Property<int?>("DeclarativeLessonsId")
                        .HasColumnType("int")
                        .HasColumnName("declarative_Lessons_ID");

                    b.Property<int?>("LessonsId")
                        .HasColumnType("int")
                        .HasColumnName("lessons_ID");

                    b.Property<int?>("PathsId")
                        .HasColumnType("int")
                        .HasColumnName("paths_ID");

                    b.Property<int?>("SubmissionsId")
                        .HasColumnType("int")
                        .HasColumnName("submissions_ID");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int")
                        .HasColumnName("users_ID");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentsId");

                    b.HasIndex("CoursesId");

                    b.HasIndex("DeclarativeLessonsId");

                    b.HasIndex("LessonsId");

                    b.HasIndex("PathsId");

                    b.HasIndex("SubmissionsId");

                    b.HasIndex("UsersId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("AlanTuring.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int>("PathsId")
                        .HasColumnType("int")
                        .HasColumnName("paths_ID");

                    b.Property<int>("CoursesIdentity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("courses_identity")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("description");

                    b.Property<int>("Price")
                        .HasColumnType("int")
                        .HasColumnName("price");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id", "PathsId")
                        .HasName("Courses_pk");

                    b.HasIndex("PathsId");

                    b.HasIndex(new[] { "Id" }, "UQ__Courses__3214EC26ABD85FA4")
                        .IsUnique();

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("AlanTuring.Models.DeclarativeLesson", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int>("PathsId")
                        .HasColumnType("int")
                        .HasColumnName("paths_ID");

                    b.Property<int>("CoursesId")
                        .HasColumnType("int")
                        .HasColumnName("courses_ID");

                    b.Property<int>("DeclarativeLessonsIdentity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Declarative_Lessons_identity")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id", "PathsId", "CoursesId")
                        .HasName("Declarative_Lessons_pk");

                    b.HasIndex("CoursesId");

                    b.HasIndex("PathsId");

                    b.HasIndex(new[] { "Id" }, "UQ__Declarat__3214EC2646CDBBEA")
                        .IsUnique();

                    b.ToTable("Declarative_Lessons");
                });

            modelBuilder.Entity("AlanTuring.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("position");

                    b.Property<decimal>("Salary")
                        .HasColumnType("money")
                        .HasColumnName("salary");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("AlanTuring.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("Datetime")
                        .HasColumnType("datetime")
                        .HasColumnName("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("AlanTuring.Models.File", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<bool?>("Accessibility")
                        .HasColumnType("bit")
                        .HasColumnName("accessibility");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("content");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Desciption")
                        .HasColumnType("text")
                        .HasColumnName("desciption");

                    b.Property<int?>("FolderChildId")
                        .HasColumnType("int")
                        .HasColumnName("folder_childID");

                    b.Property<int?>("FolderParentId")
                        .HasColumnType("int")
                        .HasColumnName("folder_parentID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("FolderParentId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("AlanTuring.Models.FilesAssignment", b =>
                {
                    b.Property<int?>("AssignmentsId")
                        .HasColumnType("int")
                        .HasColumnName("assignments_ID");

                    b.Property<int?>("FilesId")
                        .HasColumnType("int")
                        .HasColumnName("files_ID");

                    b.HasIndex("AssignmentsId");

                    b.HasIndex("FilesId");

                    b.ToTable("files_assignments");
                });

            modelBuilder.Entity("AlanTuring.Models.FilesLearningMaterial", b =>
                {
                    b.Property<int?>("FilesId")
                        .HasColumnType("int")
                        .HasColumnName("files_ID");

                    b.Property<int?>("LearningMaterialsId")
                        .HasColumnType("int")
                        .HasColumnName("learningMaterials_ID");

                    b.HasIndex("FilesId");

                    b.HasIndex("LearningMaterialsId");

                    b.ToTable("files_learningMaterials");
                });

            modelBuilder.Entity("AlanTuring.Models.Finance", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("money")
                        .HasColumnName("amount");

                    b.Property<DateTime>("Datetime")
                        .HasColumnType("datetime")
                        .HasColumnName("datetime");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("purpose");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int")
                        .HasColumnName("receiver_id");

                    b.Property<int>("SenderId")
                        .HasColumnType("int")
                        .HasColumnName("sender_id");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Finances");
                });

            modelBuilder.Entity("AlanTuring.Models.Folder", b =>
                {
                    b.Property<int>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parentID");

                    b.Property<bool>("Accessibility")
                        .HasColumnType("bit")
                        .HasColumnName("accessibility");

                    b.Property<int?>("ChildId")
                        .HasColumnType("int")
                        .HasColumnName("childID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("name");

                    b.HasKey("ParentId")
                        .HasName("PK__Folders__90658CB819BFF475");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("AlanTuring.Models.Graduation", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int>("PathsId")
                        .HasColumnType("int")
                        .HasColumnName("paths_ID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("GraduationsIdentity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("graduations_identity")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id", "PathsId")
                        .HasName("pk");

                    b.HasIndex("PathsId");

                    b.HasIndex(new[] { "Id" }, "UQ__Graduati__3214EC26F16DDBC7")
                        .IsUnique();

                    b.ToTable("Graduations");
                });

            modelBuilder.Entity("AlanTuring.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int?>("CoursesId")
                        .HasColumnType("int")
                        .HasColumnName("courses_ID");

                    b.Property<int?>("LecturersId")
                        .HasColumnType("int")
                        .HasColumnName("Lecturers_ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<int?>("PathsId")
                        .HasColumnType("int")
                        .HasColumnName("Paths_ID");

                    b.Property<int?>("StreamId")
                        .HasColumnType("int")
                        .HasColumnName("stream_ID");

                    b.HasKey("Id");

                    b.HasIndex("CoursesId");

                    b.HasIndex("LecturersId");

                    b.HasIndex("PathsId");

                    b.HasIndex("StreamId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("AlanTuring.Models.GroupConsistsOfStudent", b =>
                {
                    b.Property<int?>("GroupsId")
                        .HasColumnType("int")
                        .HasColumnName("Groups_ID");

                    b.Property<int?>("StudentsId")
                        .HasColumnType("int")
                        .HasColumnName("students_ID");

                    b.ToTable("Group_ConsistsOf_Students");
                });

            modelBuilder.Entity("AlanTuring.Models.LearningMaterial", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int?>("CoursesId")
                        .HasColumnType("int")
                        .HasColumnName("courses_ID");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int?>("DeclarativeLessonsId")
                        .HasColumnType("int")
                        .HasColumnName("declarative_Lessons_ID");

                    b.Property<int?>("LessonsId")
                        .HasColumnType("int")
                        .HasColumnName("lessons_ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<int?>("PathsId")
                        .HasColumnType("int")
                        .HasColumnName("paths_ID");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("CoursesId");

                    b.HasIndex("DeclarativeLessonsId");

                    b.HasIndex("LessonsId");

                    b.HasIndex("PathsId");

                    b.ToTable("LearningMaterials");
                });

            modelBuilder.Entity("AlanTuring.Models.Lecturer", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("money")
                        .HasColumnName("hourlyRate");

                    b.Property<string>("Speciality")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("speciality");

                    b.HasKey("Id");

                    b.ToTable("Lecturers");
                });

            modelBuilder.Entity("AlanTuring.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int>("PathsId")
                        .HasColumnType("int")
                        .HasColumnName("paths_ID");

                    b.Property<int>("CoursesId")
                        .HasColumnType("int")
                        .HasColumnName("courses_ID");

                    b.Property<int>("DeclarativeLessonsId")
                        .HasColumnType("int")
                        .HasColumnName("declarative_Lessons_ID");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("dateTime");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("description");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time(0)")
                        .HasColumnName("duration");

                    b.Property<int?>("GroupsId")
                        .HasColumnType("int")
                        .HasColumnName("Groups_ID");

                    b.Property<int?>("LecturersId")
                        .HasColumnType("int")
                        .HasColumnName("Lecturers_ID");

                    b.Property<string>("MeetingId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("MeetingID");

                    b.Property<int?>("StreamsId")
                        .HasColumnType("int")
                        .HasColumnName("Streams_ID");

                    b.HasKey("Id", "PathsId", "CoursesId", "DeclarativeLessonsId")
                        .HasName("Lessons_pk");

                    b.HasIndex("CoursesId");

                    b.HasIndex("DeclarativeLessonsId");

                    b.HasIndex("GroupsId");

                    b.HasIndex("LecturersId");

                    b.HasIndex("PathsId");

                    b.HasIndex("StreamsId");

                    b.HasIndex(new[] { "Id" }, "UQ__Lessons__3214EC26438CC650")
                        .IsUnique();

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("AlanTuring.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("AssignmentsId")
                        .HasColumnType("int")
                        .HasColumnName("assignments_id");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("content");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime")
                        .HasColumnName("date");

                    b.Property<int?>("EventsId")
                        .HasColumnType("int")
                        .HasColumnName("events_id");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.Property<int?>("SubmissionsId")
                        .HasColumnType("int")
                        .HasColumnName("submissions_id");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentsId");

                    b.HasIndex("EventsId");

                    b.HasIndex("SubmissionsId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("AlanTuring.Models.NotificationGroup", b =>
                {
                    b.Property<int?>("GroupsId")
                        .HasColumnType("int")
                        .HasColumnName("groups_ID");

                    b.Property<int?>("NotificationsId")
                        .HasColumnType("int")
                        .HasColumnName("notifications_ID");

                    b.HasIndex("GroupsId");

                    b.HasIndex("NotificationsId");

                    b.ToTable("notification_groups");
                });

            modelBuilder.Entity("AlanTuring.Models.NotificationUser", b =>
                {
                    b.Property<int?>("NotificationsId")
                        .HasColumnType("int")
                        .HasColumnName("notifications_ID");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int")
                        .HasColumnName("users_ID");

                    b.HasIndex("NotificationsId");

                    b.HasIndex("UsersId");

                    b.ToTable("notification_user");
                });

            modelBuilder.Entity("AlanTuring.Models.Path", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "UQ__Paths__72E12F1BB1F7F5E8")
                        .IsUnique();

                    b.ToTable("Paths");
                });

            modelBuilder.Entity("AlanTuring.Models.Stream", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int>("PathsId")
                        .HasColumnType("int")
                        .HasColumnName("paths_ID");

                    b.Property<int>("CoursesId")
                        .HasColumnType("int")
                        .HasColumnName("courses_ID");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int>("StrearmsIdentity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("strearms_identity")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id", "PathsId", "CoursesId")
                        .HasName("Streams_pk");

                    b.HasIndex("CoursesId");

                    b.HasIndex("PathsId");

                    b.HasIndex(new[] { "Id" }, "UQ__Streams__3214EC26827AA00E")
                        .IsUnique();

                    b.ToTable("Streams");
                });

            modelBuilder.Entity("AlanTuring.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<short?>("Discount")
                        .HasColumnType("smallint")
                        .HasColumnName("discount");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint")
                        .HasColumnName("rating");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("AlanTuring.Models.StudentParticipateLesson", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int>("PathsId")
                        .HasColumnType("int")
                        .HasColumnName("paths_ID");

                    b.Property<int>("CoursesId")
                        .HasColumnType("int")
                        .HasColumnName("courses_ID");

                    b.Property<int>("DeclarativeLessonsId")
                        .HasColumnType("int")
                        .HasColumnName("declarative_Lessons_ID");

                    b.Property<int>("LessonsId")
                        .HasColumnType("int")
                        .HasColumnName("lessons_ID");

                    b.Property<int>("StudentsId")
                        .HasColumnType("int")
                        .HasColumnName("students_ID");

                    b.Property<bool?>("Attendance")
                        .HasColumnType("bit")
                        .HasColumnName("attendance");

                    b.Property<int?>("Mark")
                        .HasColumnType("int")
                        .HasColumnName("mark");

                    b.Property<int>("StudentsParticipateLessonsIdentity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Students_Participate_Lessons_identity")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id", "PathsId", "CoursesId", "DeclarativeLessonsId", "LessonsId", "StudentsId")
                        .HasName("Students_Participate_Lessons_pk");

                    b.ToTable("Student_Participate_Lessons");
                });

            modelBuilder.Entity("AlanTuring.Models.Submission", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int>("PathsId")
                        .HasColumnType("int")
                        .HasColumnName("paths_ID");

                    b.Property<int>("CoursesId")
                        .HasColumnType("int")
                        .HasColumnName("courses_ID");

                    b.Property<int>("DeclarativeLessonsId")
                        .HasColumnType("int")
                        .HasColumnName("declarative_Lessons_ID");

                    b.Property<int>("LessonsId")
                        .HasColumnType("int")
                        .HasColumnName("lessons_ID");

                    b.Property<int>("AssignmentsId")
                        .HasColumnType("int")
                        .HasColumnName("assignments_ID");

                    b.Property<DateTime>("Datetime")
                        .HasColumnType("datetime")
                        .HasColumnName("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Mark")
                        .HasColumnType("int")
                        .HasColumnName("mark");

                    b.Property<int?>("StudentsId")
                        .HasColumnType("int")
                        .HasColumnName("students_ID");

                    b.Property<int>("SubmissionsIdentity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("submissions_identity")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id", "PathsId", "CoursesId", "DeclarativeLessonsId", "LessonsId", "AssignmentsId")
                        .HasName("Submissions_pk");

                    b.HasIndex("AssignmentsId");

                    b.HasIndex("CoursesId");

                    b.HasIndex("DeclarativeLessonsId");

                    b.HasIndex("LessonsId");

                    b.HasIndex("PathsId");

                    b.HasIndex("StudentsId");

                    b.HasIndex(new[] { "Id" }, "UQ__Submissi__3214EC26FC7F699B")
                        .IsUnique();

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("AlanTuring.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Cv")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("cv");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("DOB");

                    b.Property<string>("FirstName")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("firstName");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("lastName");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("mail");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasMaxLength(9)
                        .IsUnicode(false)
                        .HasColumnType("char(9)")
                        .HasColumnName("phone")
                        .IsFixedLength(true);

                    b.Property<byte[]>("Picture")
                        .HasColumnType("image")
                        .HasColumnName("picture");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Mail" }, "UQ__Users__7A2129048A1A65BF")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AlanTuring.Models.Assignment", b =>
                {
                    b.HasOne("AlanTuring.Models.Course", "Courses")
                        .WithMany("Assignments")
                        .HasForeignKey("CoursesId")
                        .HasConstraintName("FK__Assignmen__cours__7E37BEF6")
                        .HasPrincipalKey("Id")
                        .IsRequired();

                    b.HasOne("AlanTuring.Models.DeclarativeLesson", "DeclarativeLessons")
                        .WithMany("Assignments")
                        .HasForeignKey("DeclarativeLessonsId")
                        .HasConstraintName("FK__Assignmen__decla__5AEE82B9")
                        .HasPrincipalKey("Id")
                        .IsRequired();

                    b.HasOne("AlanTuring.Models.Lesson", "Lessons")
                        .WithMany("Assignments")
                        .HasForeignKey("LessonsId")
                        .HasConstraintName("FK__Assignmen__lesso__00200768")
                        .HasPrincipalKey("Id")
                        .IsRequired();

                    b.HasOne("AlanTuring.Models.Path", "Paths")
                        .WithMany("Assignments")
                        .HasForeignKey("PathsId")
                        .HasConstraintName("FK__Assignmen__paths__5CD6CB2B")
                        .IsRequired();

                    b.Navigation("Courses");

                    b.Navigation("DeclarativeLessons");

                    b.Navigation("Lessons");

                    b.Navigation("Paths");
                });

            modelBuilder.Entity("AlanTuring.Models.Chat", b =>
                {
                    b.HasOne("AlanTuring.Models.Group", "GroupReceiver")
                        .WithMany("Chats")
                        .HasForeignKey("GroupReceiverId")
                        .HasConstraintName("FK__Chats__group_rec__5DCAEF64");

                    b.HasOne("AlanTuring.Models.User", "UserReceiver")
                        .WithMany("ChatUserReceivers")
                        .HasForeignKey("UserReceiverId")
                        .HasConstraintName("FK__Chats__user_rece__32AB8735");

                    b.HasOne("AlanTuring.Models.User", "UserSender")
                        .WithMany("ChatUserSenders")
                        .HasForeignKey("UserSenderId")
                        .HasConstraintName("FK__Chats__user_send__339FAB6E");

                    b.Navigation("GroupReceiver");

                    b.Navigation("UserReceiver");

                    b.Navigation("UserSender");
                });

            modelBuilder.Entity("AlanTuring.Models.Comment", b =>
                {
                    b.HasOne("AlanTuring.Models.Assignment", "Assignments")
                        .WithMany("Comments")
                        .HasForeignKey("AssignmentsId")
                        .HasConstraintName("FK__Comments__assign__60A75C0F")
                        .HasPrincipalKey("Id");

                    b.HasOne("AlanTuring.Models.Course", "Courses")
                        .WithMany("Comments")
                        .HasForeignKey("CoursesId")
                        .HasConstraintName("FK__Comments__course__0F624AF8")
                        .HasPrincipalKey("Id");

                    b.HasOne("AlanTuring.Models.DeclarativeLesson", "DeclarativeLessons")
                        .WithMany("Comments")
                        .HasForeignKey("DeclarativeLessonsId")
                        .HasConstraintName("FK__Comments__declar__628FA481")
                        .HasPrincipalKey("Id");

                    b.HasOne("AlanTuring.Models.Lesson", "Lessons")
                        .WithMany("Comments")
                        .HasForeignKey("LessonsId")
                        .HasConstraintName("FK__Comments__lesson__114A936A")
                        .HasPrincipalKey("Id");

                    b.HasOne("AlanTuring.Models.Path", "Paths")
                        .WithMany("Comments")
                        .HasForeignKey("PathsId")
                        .HasConstraintName("FK__Comments__paths___6477ECF3");

                    b.HasOne("AlanTuring.Models.Submission", "Submissions")
                        .WithMany("Comments")
                        .HasForeignKey("SubmissionsId")
                        .HasConstraintName("FK__Comments__submis__656C112C")
                        .HasPrincipalKey("Id");

                    b.HasOne("AlanTuring.Models.User", "Users")
                        .WithMany("Comments")
                        .HasForeignKey("UsersId")
                        .HasConstraintName("FK__Comments__users___0C85DE4D");

                    b.Navigation("Assignments");

                    b.Navigation("Courses");

                    b.Navigation("DeclarativeLessons");

                    b.Navigation("Lessons");

                    b.Navigation("Paths");

                    b.Navigation("Submissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("AlanTuring.Models.Course", b =>
                {
                    b.HasOne("AlanTuring.Models.Path", "Paths")
                        .WithMany("Courses")
                        .HasForeignKey("PathsId")
                        .HasConstraintName("FK__Courses__paths_I__52593CB8")
                        .IsRequired();

                    b.Navigation("Paths");
                });

            modelBuilder.Entity("AlanTuring.Models.DeclarativeLesson", b =>
                {
                    b.HasOne("AlanTuring.Models.Course", "Courses")
                        .WithMany("DeclarativeLessons")
                        .HasForeignKey("CoursesId")
                        .HasConstraintName("FK__Declarati__cours__5AEE82B9")
                        .HasPrincipalKey("Id")
                        .IsRequired();

                    b.HasOne("AlanTuring.Models.Path", "Paths")
                        .WithMany("DeclarativeLessons")
                        .HasForeignKey("PathsId")
                        .HasConstraintName("FK__Declarati__paths__693CA210")
                        .IsRequired();

                    b.Navigation("Courses");

                    b.Navigation("Paths");
                });

            modelBuilder.Entity("AlanTuring.Models.Employee", b =>
                {
                    b.HasOne("AlanTuring.Models.User", "IdNavigation")
                        .WithOne("Employee")
                        .HasForeignKey("AlanTuring.Models.Employee", "Id")
                        .HasConstraintName("FK__Employees__id__778AC167")
                        .IsRequired();

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("AlanTuring.Models.File", b =>
                {
                    b.HasOne("AlanTuring.Models.Folder", "FolderParent")
                        .WithMany("Files")
                        .HasForeignKey("FolderParentId")
                        .HasConstraintName("FK__Files__folder_pa__160F4887");

                    b.Navigation("FolderParent");
                });

            modelBuilder.Entity("AlanTuring.Models.FilesAssignment", b =>
                {
                    b.HasOne("AlanTuring.Models.Assignment", "Assignments")
                        .WithMany()
                        .HasForeignKey("AssignmentsId")
                        .HasConstraintName("FK__files_ass__assig__6C190EBB")
                        .HasPrincipalKey("Id");

                    b.HasOne("AlanTuring.Models.File", "Files")
                        .WithMany()
                        .HasForeignKey("FilesId")
                        .HasConstraintName("FK__files_ass__files__17F790F9");

                    b.Navigation("Assignments");

                    b.Navigation("Files");
                });

            modelBuilder.Entity("AlanTuring.Models.FilesLearningMaterial", b =>
                {
                    b.HasOne("AlanTuring.Models.File", "Files")
                        .WithMany()
                        .HasForeignKey("FilesId")
                        .HasConstraintName("FK__files_lea__files__208CD6FA");

                    b.HasOne("AlanTuring.Models.LearningMaterial", "LearningMaterials")
                        .WithMany()
                        .HasForeignKey("LearningMaterialsId")
                        .HasConstraintName("FK__files_lea__learn__6EF57B66");

                    b.Navigation("Files");

                    b.Navigation("LearningMaterials");
                });

            modelBuilder.Entity("AlanTuring.Models.Finance", b =>
                {
                    b.HasOne("AlanTuring.Models.User", "Receiver")
                        .WithMany("FinanceReceivers")
                        .HasForeignKey("ReceiverId")
                        .HasConstraintName("FK__Finances__receiv__2EDAF651")
                        .IsRequired();

                    b.HasOne("AlanTuring.Models.User", "Sender")
                        .WithMany("FinanceSenders")
                        .HasForeignKey("SenderId")
                        .HasConstraintName("FK__Finances__sender__2FCF1A8A")
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("AlanTuring.Models.Graduation", b =>
                {
                    b.HasOne("AlanTuring.Models.Path", "Paths")
                        .WithMany("Graduations")
                        .HasForeignKey("PathsId")
                        .HasConstraintName("FK__Graduatio__paths__4D94879B")
                        .IsRequired();

                    b.Navigation("Paths");
                });

            modelBuilder.Entity("AlanTuring.Models.Group", b =>
                {
                    b.HasOne("AlanTuring.Models.Course", "Courses")
                        .WithMany("Groups")
                        .HasForeignKey("CoursesId")
                        .HasConstraintName("FK__Groups__courses___6754599E")
                        .HasPrincipalKey("Id");

                    b.HasOne("AlanTuring.Models.Lecturer", "Lecturers")
                        .WithMany("Groups")
                        .HasForeignKey("LecturersId")
                        .HasConstraintName("FK__Groups__Lecturer__73BA3083");

                    b.HasOne("AlanTuring.Models.Path", "Paths")
                        .WithMany("Groups")
                        .HasForeignKey("PathsId")
                        .HasConstraintName("FK__Groups__Paths_ID__74AE54BC");

                    b.HasOne("AlanTuring.Models.Stream", "Stream")
                        .WithMany("Groups")
                        .HasForeignKey("StreamId")
                        .HasConstraintName("FK__Groups__stream_I__656C112C")
                        .HasPrincipalKey("Id");

                    b.Navigation("Courses");

                    b.Navigation("Lecturers");

                    b.Navigation("Paths");

                    b.Navigation("Stream");
                });

            modelBuilder.Entity("AlanTuring.Models.LearningMaterial", b =>
                {
                    b.HasOne("AlanTuring.Models.Course", "Courses")
                        .WithMany("LearningMaterials")
                        .HasForeignKey("CoursesId")
                        .HasConstraintName("FK__LearningM__cours__1CBC4616")
                        .HasPrincipalKey("Id");

                    b.HasOne("AlanTuring.Models.DeclarativeLesson", "DeclarativeLessons")
                        .WithMany("LearningMaterials")
                        .HasForeignKey("DeclarativeLessonsId")
                        .HasConstraintName("FK__LearningM__decla__778AC167")
                        .HasPrincipalKey("Id");

                    b.HasOne("AlanTuring.Models.Lesson", "Lessons")
                        .WithMany("LearningMaterials")
                        .HasForeignKey("LessonsId")
                        .HasConstraintName("FK__LearningM__lesso__1EA48E88")
                        .HasPrincipalKey("Id");

                    b.HasOne("AlanTuring.Models.Path", "Paths")
                        .WithMany("LearningMaterials")
                        .HasForeignKey("PathsId")
                        .HasConstraintName("FK__LearningM__paths__797309D9");

                    b.Navigation("Courses");

                    b.Navigation("DeclarativeLessons");

                    b.Navigation("Lessons");

                    b.Navigation("Paths");
                });

            modelBuilder.Entity("AlanTuring.Models.Lecturer", b =>
                {
                    b.HasOne("AlanTuring.Models.User", "IdNavigation")
                        .WithOne("Lecturer")
                        .HasForeignKey("AlanTuring.Models.Lecturer", "Id")
                        .HasConstraintName("FK__Lecturers__id__628FA481")
                        .IsRequired();

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("AlanTuring.Models.Lesson", b =>
                {
                    b.HasOne("AlanTuring.Models.Course", "Courses")
                        .WithMany("Lessons")
                        .HasForeignKey("CoursesId")
                        .HasConstraintName("FK__Lessons__courses__6E01572D")
                        .HasPrincipalKey("Id")
                        .IsRequired();

                    b.HasOne("AlanTuring.Models.DeclarativeLesson", "DeclarativeLessons")
                        .WithMany("Lessons")
                        .HasForeignKey("DeclarativeLessonsId")
                        .HasConstraintName("FK__Lessons__declara__6D0D32F4")
                        .HasPrincipalKey("Id")
                        .IsRequired();

                    b.HasOne("AlanTuring.Models.Group", "Groups")
                        .WithMany("Lessons")
                        .HasForeignKey("GroupsId")
                        .HasConstraintName("FK__Lessons__Groups___70DDC3D8");

                    b.HasOne("AlanTuring.Models.Lecturer", "Lecturers")
                        .WithMany("Lessons")
                        .HasForeignKey("LecturersId")
                        .HasConstraintName("FK__Lessons__Lecture__6FE99F9F");

                    b.HasOne("AlanTuring.Models.Path", "Paths")
                        .WithMany("Lessons")
                        .HasForeignKey("PathsId")
                        .HasConstraintName("FK__Lessons__paths_I__6EF57B66")
                        .IsRequired();

                    b.HasOne("AlanTuring.Models.Stream", "Streams")
                        .WithMany("Lessons")
                        .HasForeignKey("StreamsId")
                        .HasConstraintName("FK__Lessons__Streams__71D1E811")
                        .HasPrincipalKey("Id");

                    b.Navigation("Courses");

                    b.Navigation("DeclarativeLessons");

                    b.Navigation("Groups");

                    b.Navigation("Lecturers");

                    b.Navigation("Paths");

                    b.Navigation("Streams");
                });

            modelBuilder.Entity("AlanTuring.Models.Notification", b =>
                {
                    b.HasOne("AlanTuring.Models.Assignment", "Assignments")
                        .WithMany("Notifications")
                        .HasForeignKey("AssignmentsId")
                        .HasConstraintName("FK__Notificat__assig__04E4BC85")
                        .HasPrincipalKey("Id");

                    b.HasOne("AlanTuring.Models.Event", "Events")
                        .WithMany("Notifications")
                        .HasForeignKey("EventsId")
                        .HasConstraintName("FK__Notificat__event__2BFE89A6");

                    b.HasOne("AlanTuring.Models.Submission", "Submissions")
                        .WithMany("Notifications")
                        .HasForeignKey("SubmissionsId")
                        .HasConstraintName("FK__Notificat__submi__06CD04F7")
                        .HasPrincipalKey("Id");

                    b.Navigation("Assignments");

                    b.Navigation("Events");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("AlanTuring.Models.NotificationGroup", b =>
                {
                    b.HasOne("AlanTuring.Models.Group", "Groups")
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .HasConstraintName("FK__notificat__group__01142BA1");

                    b.HasOne("AlanTuring.Models.Notification", "Notifications")
                        .WithMany()
                        .HasForeignKey("NotificationsId")
                        .HasConstraintName("FK__notificat__notif__02084FDA");

                    b.Navigation("Groups");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("AlanTuring.Models.NotificationUser", b =>
                {
                    b.HasOne("AlanTuring.Models.Notification", "Notifications")
                        .WithMany()
                        .HasForeignKey("NotificationsId")
                        .HasConstraintName("FK__notificat__notif__02FC7413");

                    b.HasOne("AlanTuring.Models.User", "Users")
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .HasConstraintName("FK__notificat__users__367C1819");

                    b.Navigation("Notifications");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("AlanTuring.Models.Stream", b =>
                {
                    b.HasOne("AlanTuring.Models.Course", "Courses")
                        .WithMany("Streams")
                        .HasForeignKey("CoursesId")
                        .HasConstraintName("FK__Streams__courses__571DF1D5")
                        .HasPrincipalKey("Id")
                        .IsRequired();

                    b.HasOne("AlanTuring.Models.Path", "Paths")
                        .WithMany("Streams")
                        .HasForeignKey("PathsId")
                        .HasConstraintName("FK__Streams__paths_I__5629CD9C")
                        .IsRequired();

                    b.Navigation("Courses");

                    b.Navigation("Paths");
                });

            modelBuilder.Entity("AlanTuring.Models.Student", b =>
                {
                    b.HasOne("AlanTuring.Models.User", "IdNavigation")
                        .WithOne("Student")
                        .HasForeignKey("AlanTuring.Models.Student", "Id")
                        .HasConstraintName("FK__Students__id__74AE54BC")
                        .IsRequired();

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("AlanTuring.Models.Submission", b =>
                {
                    b.HasOne("AlanTuring.Models.Assignment", "Assignments")
                        .WithMany("Submissions")
                        .HasForeignKey("AssignmentsId")
                        .HasConstraintName("FK__Submissio__assig__0A9D95DB")
                        .HasPrincipalKey("Id")
                        .IsRequired();

                    b.HasOne("AlanTuring.Models.Course", "Courses")
                        .WithMany("Submissions")
                        .HasForeignKey("CoursesId")
                        .HasConstraintName("FK__Submissio__cours__04E4BC85")
                        .HasPrincipalKey("Id")
                        .IsRequired();

                    b.HasOne("AlanTuring.Models.DeclarativeLesson", "DeclarativeLessons")
                        .WithMany("Submissions")
                        .HasForeignKey("DeclarativeLessonsId")
                        .HasConstraintName("FK__Submissio__decla__0C85DE4D")
                        .HasPrincipalKey("Id")
                        .IsRequired();

                    b.HasOne("AlanTuring.Models.Lesson", "Lessons")
                        .WithMany("Submissions")
                        .HasForeignKey("LessonsId")
                        .HasConstraintName("FK__Submissio__lesso__06CD04F7")
                        .HasPrincipalKey("Id")
                        .IsRequired();

                    b.HasOne("AlanTuring.Models.Path", "Paths")
                        .WithMany("Submissions")
                        .HasForeignKey("PathsId")
                        .HasConstraintName("FK__Submissio__paths__0E6E26BF")
                        .IsRequired();

                    b.HasOne("AlanTuring.Models.Student", "Students")
                        .WithMany("Submissions")
                        .HasForeignKey("StudentsId")
                        .HasConstraintName("FK__Submissio__stude__0F624AF8");

                    b.Navigation("Assignments");

                    b.Navigation("Courses");

                    b.Navigation("DeclarativeLessons");

                    b.Navigation("Lessons");

                    b.Navigation("Paths");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("AlanTuring.Models.Assignment", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Notifications");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("AlanTuring.Models.Course", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Comments");

                    b.Navigation("DeclarativeLessons");

                    b.Navigation("Groups");

                    b.Navigation("LearningMaterials");

                    b.Navigation("Lessons");

                    b.Navigation("Streams");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("AlanTuring.Models.DeclarativeLesson", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Comments");

                    b.Navigation("LearningMaterials");

                    b.Navigation("Lessons");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("AlanTuring.Models.Event", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("AlanTuring.Models.Folder", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("AlanTuring.Models.Group", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("AlanTuring.Models.Lecturer", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("AlanTuring.Models.Lesson", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Comments");

                    b.Navigation("LearningMaterials");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("AlanTuring.Models.Path", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Comments");

                    b.Navigation("Courses");

                    b.Navigation("DeclarativeLessons");

                    b.Navigation("Graduations");

                    b.Navigation("Groups");

                    b.Navigation("LearningMaterials");

                    b.Navigation("Lessons");

                    b.Navigation("Streams");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("AlanTuring.Models.Stream", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("AlanTuring.Models.Student", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("AlanTuring.Models.Submission", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("AlanTuring.Models.User", b =>
                {
                    b.Navigation("ChatUserReceivers");

                    b.Navigation("ChatUserSenders");

                    b.Navigation("Comments");

                    b.Navigation("Employee");

                    b.Navigation("FinanceReceivers");

                    b.Navigation("FinanceSenders");

                    b.Navigation("Lecturer");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
